site_name: 読書記録
theme:
  name: 'gitbook'

nav:
  - Home: 'index.md'
  - Statistics:
    - '統計学基礎': 'Statistics/statistics-basic.md'
  - Databae:
    - 'データベース基礎': 'Database/database-basic.md'
  - Python:
    - 'Python文法': 'Python/python-grammerhigi.md'
    - 'NumPy': 'Python/numpy.md'