site_name: 読書記録

nav:
  - Home: 'index.md'
  - Statistics:
    - '統計学基礎': 'Statistics/statistics-basic.md'
  - Databae:
    - 'データベース基礎': 'Database/database-basic.md'
  - Python:
    - 'Python文法': 'Python/python-grammer.md'
    - 'NumPy': 'Python/numpy.md'


theme:
  name: gitbook
  palette:
    primary: green


markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true

extra_javascript: 
  - src/js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

