site_name: データ分析勉強まとめ

nav:
  - Home: 'index.md'
  - Statistics:
    - '統計学基礎': 'Statistics/statistics-basic.md'
  - Databae:
    - 'データベース基礎': 'Database/database-basic.md'
  - Python:
    - '型ヒント': 'Python/typing-hint.md'
    - 'NumPy': 'Python/numpy.md'
  - Development Tools:
    - 'Git': 'DevTools/git.md'
    - 'GitLab': 'DevTools/gitlab.md'
    - 'Docker': 'DevTools/docker.md'

theme:
  name: gitbook
  palette:
    primary: green


markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true

extra_javascript: 
  - src/js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

